GET https://szdekilrmk.execute-api.us-west-1.amazonaws.com/dev/spaces
###

GET https://szdekilrmk.execute-api.us-west-1.amazonaws.com/dev/spaces?id=f05952eb-4a33-4508-940a-47c88f7cf5b9
###

POST https://szdekilrmk.execute-api.us-west-1.amazonaws.com/dev/spaces
Content-Type: application/json

{ "location": "NYC", "name": "New York City" }
###

PUT https://szdekilrmk.execute-api.us-west-1.amazonaws.com/dev/spaces?id=f05952eb-4a33-4508-940a-47c88f7cf5b9
Content-Type: application/json

{ "location": "Albatroz", "name": "Alba Beach" }
###

DELETE https://szdekilrmk.execute-api.us-west-1.amazonaws.com/dev/spaces?id=f05952eb-4a33-4508-940a-47c88f7cf5b9
###
